name: Compilar API UTVM

on:
  pull_request:
    branches: [ main ]

env:
  IMAGE_BASE_NAME: aminespinoza/apiutvm:latest

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: src/API_UTVM

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Build Docker NET image
      run: |
        docker build --platform linux --tag $IMAGE_BASE_NAME .
